### PR TITLE
Providing an alternate way to detect log creation via polling.

### PR DESCRIPTION
**Pull request by SaculRennorb**
This could be a solution for #37 , providing the option to select weather or not to use polling instead of the FSW to detect new logs.

I did some initial testing, but by no means verified that literally everything works as expected.

I had to fight VS quite hard to not reformat everything the editor touches, so i hope that's all good. Also I'm not sure where best to put the checkbox, as normal users basically don't need to interact with it. Also also I wasn't sure on where to put the utility class for observing changes, so i just put it at the bottom of MainForm.

### CODE REVIEW

**Comment by SaculRennorb** [comment]
I also fixed a typo `minimised` -> `minimized`

**Comment by Plenyx** [comment]
Thank you so much for your help.

> I also fixed a typo `minimised` -> `minimized`


Not really a typo, it is British spelling, the same reason that I use `Colour` over `Color`

**Comment by SaculRennorb** [comment]
Huh, interesting.
I've never seen that version written anywhere, but of course feel free to just change it back.

**Review by Plenyx — APPROVED** [review]

**Comment by Plenyx** [comment]
> Huh, interesting. I've never seen that version written anywhere, but of course feel free to just change it back.

There are more inconsistencies between AM and BR spelling within the code, but it is fine as is.

**Pull request merged**
